=== cameroncros/BeagleSight/default_configs/target_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="GUID">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="location">
        <xs:sequence>
            <xs:element name="id" type="GUID" />
            <xs:element name="target_id" type="GUID" />
            <xs:element name="description" minOccurs="0" type="xs:string" />
            <xs:element name="latitude" type="xs:float" />
            <xs:element name="longitude" type="xs:float" />
            <xs:element name="altitude" type="xs:float" />
            <xs:element name="lat_lng_accuracy" minOccurs="0" type="xs:float" />
            <xs:element name="altitude_accuracy" minOccurs="0" type="xs:float" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="target">
        <xs:sequence>
            <xs:element name="id" type="GUID" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="builtin" type="xs:boolean" />
            <xs:element name="location" type="location" />
            <xs:element name="shoot_position" maxOccurs="unbounded" minOccurs="0" type="location" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="targets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="target" type="target" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cameroncros/BeagleSight/default_configs/targets.xml
<?xml version="1.0" encoding="UTF-8" ?>
<targets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="target_schema.xsd">
    <target>
        <id>403d084b-a611-4347-bbb0-b748cd5a4fa5</id>
        <name>Example Target</name>
        <builtin>true</builtin>

        <location>
            <id>2397b261-d2b0-4992-928a-935435805034</id>
            <target_id>403d084b-a611-4347-bbb0-b748cd5a4fa5</target_id>
            <description>Target at a fake location</description>
            <longitude>123.4567</longitude>
            <latitude>56.789</latitude>
            <altitude>300</altitude>
            <lat_lng_accuracy>3</lat_lng_accuracy>
            <altitude_accuracy>2</altitude_accuracy>
        </location>

        <shoot_position>
            <id>d0cdfa5c-ea15-4df2-bc12-5df785354763</id>
            <target_id>403d084b-a611-4347-bbb0-b748cd5a4fa5</target_id>
            <description>Example Shoot Pos 1</description>
            <longitude>123.4568</longitude>
            <latitude>56.780</latitude>
            <altitude>330</altitude>
            <lat_lng_accuracy>5</lat_lng_accuracy>
            <altitude_accuracy>1</altitude_accuracy>
        </shoot_position>

        <shoot_position>
            <id>40f4bafc-4dab-4a21-abfb-f1dbeffbe9b3</id>
            <target_id>403d084b-a611-4347-bbb0-b748cd5a4fa5</target_id>
            <description>Example Shoot Pos 2</description>
            <longitude>123.4668</longitude>
            <latitude>56.7809</latitude>
            <altitude>270</altitude>
            <lat_lng_accuracy>1</lat_lng_accuracy>
            <altitude_accuracy>4</altitude_accuracy>
        </shoot_position>
    </target>
</targets>
